name: Check Style
on: push

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: latest

      - name: Install tools
        run: python -m pip install --upgrade pip pycodestyle

      - name: Check Style
        run: pycodestyle --first *.py
